version: latest

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: schema
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: api
    depends_on:
      - postgres
    build: ./
    ports:
      - 8080:8080
    environment:
      - JWT_TOKEN=256-bit-token
      - DB_HOST=host
      - DB_PORT=5432
      - DB_USER=
      - DB_PASS=pass
      - DB_SCHEMA=schema
    volumes:
      - maven-repo:/root/.m2

volumes:
  postgres:
    driver: local
  maven-repo:
    driver: local